config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :books
  resources :users
  resources :transaction, except: :show
  namespace :transaction do
    get "borrow"
    get "list"
    get "return_book"
  end
  # get "borrow", to: "transaction#borrow"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  attr_accessor :borrow_date, :return_date
  attr_accessor :search

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :genre, :available)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController

  def index

  end

  def show

  end

  def return_book
    id = params[:transaction][:transaction_id]
    Transaction.find(id).update(returned: Date.today)
    redirect_to transaction_list_path

  end

  def list
    filter = check_filter()
    if filter
      @transaction = filter
    else
      if params['search'].nil?
        @transaction = Transaction.all
      else
        @transaction =
          Transaction
          .joins(:book)
          .joins(:user).
          where('title like ? OR name like ?', "%#{params['search']}%",  "%#{params['search']}%")
      end
    end
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.pinjam = Date.new(borrow_date[0], borrow_date[1], borrow_date[2])
    @transaction.kembali = Date.new(return_date[0], return_date[1], return_date[2])
      if @transaction.kembali <= @transaction.pinjam
      flash[:error] = "Error. Tanggal kembali harus > tanggal peminjaman"
      redirect_to transaction_borrow_path
    else
      if @transaction.save
        flash[:info] = "Peminjaman tercatat"
      else
        flash[:error] = "Error. Peminjaman tidak tercatat"
      end
      redirect_to transaction_borrow_path
    end
  end

  def borrow
    @user = User.all
    @book = Book.all
    @transaction = Transaction.new
  end

  private
  def transaction_params
    params.require(:transaction).permit(:user_id, :book_id, :pinjam, :kembali)
  end

  def borrow_date
    [
      params.require(:pinjam)['pinjam(1i)'].to_i,
      params.require(:pinjam)['pinjam(2i)'].to_i,
      params.require(:pinjam)['pinjam(3i)'].to_i
    ]
  end

  def return_date
    [
      params.require(:kembali)['kembali(1i)'].to_i,
      params.require(:kembali)['kembali(2i)'].to_i,
      params.require(:kembali)['kembali(3i)'].to_i
    ]
  end

  def check_filter
    if params[:filter] == "late"
      Transaction.where("returned > kembali")
    elsif params[:filter] == "unreturned"
      Transaction.where('returned is null')
    else
      nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.number_field :available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.genre %></td>
        <td><%= book.available %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Available:</strong>
  <%= @book.available %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booktrnsctn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div id="flash" class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%=button_to :list, transaction_list_path, class: "btn-primary", method: :get  %>
<%=button_to :borrow, transaction_borrow_path, class: "btn-primary", method: :get  %>

app/views/transaction/borrow.html.erb
<h1>Borrow</h1>
<%=button_to :home, root_path, class: "btn-primary", method: :get  %>

<h2>Masukkan detail peminjaman<h2>
<%= form_for :transaction, :url => { :controller => "transaction", :action => "create" }, :html => {:method => :post} do |f| %>
  Nama: <%= f.select(:user_id, options_for_select(@user.map{|c| [c.name, c.id]}, @user)) %></br>
  Buku: <%= f.select(:book_id, options_for_select(@book.map{|c| [c.title, c.id]}, @book)) %></br>
  Tanggal Pinjam: <%= date_select :pinjam, :pinjam , :class => 'datepicker' %></br>
  Tanggal Kembali: <%= date_select :kembali, :kembali , :class => 'datepicker' %></br>
  <%= f.submit :Pinjam %>
<% end %>

app/views/transaction/home.html.erb
<h1>Transaction</h1>

app/views/transaction/index.html.erb
<h1>Transactions</h1>

app/views/transaction/list.html.erb
<h1>List</h1>
<%=button_to(:home, root_path, class: "btn-primary", method: :get)  %>


<h2>Masukkan detail pengembalian<h2>
<%= form_for :transaction, :url => { :controller => "transaction", :action => "list" }, :html => {:method => :get} do |f| %>
  <%= f.label :search %>:
  <%= text_field_tag :search %><br/>
<% end %>
<%= link_to '<button type="button">Filter Terlambat</button>'.html_safe, transaction_list_path(filter: :late) %>
<%= link_to '<button type="button">Filter Belum kembali</button>'.html_safe, transaction_list_path(filter: :unreturned) %>
<%= link_to '<button type="button">Clear Filter</button>'.html_safe, transaction_list_path %>
<table class="table">
  <thead>
    <tr>
      <th>Nama</th>
      <th>Buku</th>
      <th>Tanggal Pinjam</th>
      <th>Tanggal Kembali</th>
      <th>Tanggal Dikembalikan</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @transaction.each do |t| %>
    <tr class=<%= t.returned.nil? ? "" : (t.returned > t.kembali ? "late" : "") %>>
      <td><%= t.user.name %></td>
      <td><%= t.book.title %></td>
      <td><%= t.pinjam %></td>
      <td><%= t.kembali %></td>
      <td><%= t.returned %></td>
      <%= form_for :transaction, :url => { :controller => "transaction", :action => "return_book" }, :html => {:method => :get} do |f| %>
      <%= f.hidden_field :transaction_id, value: t.id %>
      <td><%= t.returned.nil? ? f.submit(:return) : "-" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/transaction/show.html.erb
<h1>eys</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>